theme: jekyll-theme-slate
title: This is the personal homepage of Komang Diah Cahya Utami, Hokudai exchange student from Indonesia
description: What you will find here are links to projects, publications, and repositories related to the former. Expect some delay in reporting!
plugins:
  - jemoji
url: "https://diahcahyautami.github.io/"
markdown: kramdown