theme: beautiful-jekyll
title: This is the personal homepage of Cahya, a third year Management student at IPB University
description: What you will find here are some stories about my education and (maybe soon) career journey!
plugins:
  - jemoji
  - jekyll-remote-theme
url: "https://diahcahyautami.github.io/"
markdown: kramdown